use_frameworks!

platform :ios, '10.0'

target 'SwiftCompletionSource_Example' do
  pod 'SwiftCompletionSource', :path => '../'

  target 'SwiftCompletionSource_Tests' do
    inherit! :search_paths

    
  end
end
